export {default as Home} from './Home.jsx'
export {default as Orders} from './Orders.jsx'
export {default as Auth} from './Auth.jsx'
export {default as Tailors} from './Tailors.jsx'
export {default as Products} from './Products.jsx'
export {default as Dashboard} from './Dashboard.jsx'